#!/bin/tcsh
#
/bin/rm -f *.o 
/bin/rm -f *.f 
/bin/rm -f imlib2k.a
./fsplit imsubs2000.for
./fsplit imsubs2.for
/usr/local/gfortran/bin/gfortran -O -w -fno-second-underscore -c *.f
#ar crs imlib2k.a *.o
ar crs libim2k.a *.o
/bin/rm -f *.o 
/bin/rm -f *.f 
