#!/bin/bash
#
# Build everything in the right order
#
# The args are passed to cmake

################################################################################
# Configuration
################################################################################

# Set the default gravis prefix
PREFIX=$1

echo '*============================================================================*'
echo '| Configuration'
echo '+----------------------------------------------------------------------------+'
echo '|                                                                            |'

if [ $# -lt 1 ]
then
	echo 'No prefix is specified, the default prefix PREFIX='$HOME'/2dx is met'
       	PREFIX=~/2dx	
fi



# And create build dirs here
BUILD=$PREFIX/build
SRC=$(pwd)
BUILD_LIST="
lib/src/conf 
lib/src/extentions 
lib/src/mrcImage 
lib/src/widgets
"

echo 'The build dir is' ${BUILD}
# check if the build dir exists
if [ ! -e $BUILD ]; then
	echo 'The build dir does not exist, therefore it will be created.' 
	mkdir -p $BUILD
fi

echo 'The source dir is' ${SRC}
echo '*============================================================================*'
echo ''
echo ''
echo ''
echo ''

################################################################################
# Fortran
################################################################################
APP=kernel/mrc
echo '*============================================================================*'
echo '| ' ${APP}
echo '+----------------------------------------------------------------------------+'
echo '| prepare                                                                    |'
cd ${SRC}/${APP}
echo 'workinkg directory: '
pwd
echo '+----------------------------------------------------------------------------+'
echo '| configure                                                                  |'
echo ./configure || (echo "Configure failed for" $APP ; read)
./configure || (echo "Configure failed for" $APP ; read)
echo ''
echo '+----------------------------------------------------------------------------+'
echo '| make                                                                       |'
make VERBOSE=1 -j1 || (echo "Build failed for $APP"; read)
#echo ''
#echo '+----------------------------------------------------------------------------+'
#echo '| make install                                                               |'
#make VERBOSE=1 -j1 install || (echo "Install failed for $APP"; read)
echo '*============================================================================*'
echo ''
echo ''
echo ''
echo ''


################################################################################
# CMake Tools
################################################################################

APP=cmake
echo '*============================================================================*'
echo '| ' ${APP}
echo '+----------------------------------------------------------------------------+'
echo '| prepare                                                                    |'
cd ${SRC}/tools/cmake
echo 'workinkg directory: '
pwd
echo '+----------------------------------------------------------------------------+'
echo '| configure                                                                  |'
echo cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} . || (echo "Configure failed for" $APP ; read)
cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} . || (echo "Configure failed for" $APP ; read)
echo ''
echo '+----------------------------------------------------------------------------+'
echo '| make                                                                       |'
make VERBOSE=1 -j1 || (echo "Build failed for $APP"; read)
echo ''
echo '+----------------------------------------------------------------------------+'
echo '| make install                                                               |'
make VERBOSE=1 -j1 install || (echo "Install failed for $APP"; read)
echo '*============================================================================*'
echo ''
echo ''
echo ''
echo ''

################################################################################
# Libs
################################################################################


for TARGET in $BUILD_LIST
do
	  APP=$(echo $TARGET | awk -F/ '{print $NF}')
          echo '*============================================================================*'
          echo '| ' ${APP}
          echo '+----------------------------------------------------------------------------+'
          echo '| prepare                                                                    |'
          cd ${SRC}/${TARGET} || (echo "Build failed for $APP, it seems the sources are not in ${SRC}/${APP}."; read)
          mkdir -p ${BUILD}/${APP}
          cd ${BUILD}/${APP}
          echo ''
          echo '+----------------------------------------------------------------------------+'
          echo '| configure                                                                  |'
          echo cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} ${*} ${SRC}/${TARGET} || (echo "Configure failed for $APP"; read)
          cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} ${*} ${SRC}/${TARGET} || (echo "Configure failed for $APP"; read)
          echo ''
          echo '+----------------------------------------------------------------------------+'
          echo '| make                                                                       |'
          make VERBOSE=1 -j1 || (echo "Build failed for $APP"; read)
          echo ''
          echo '+----------------------------------------------------------------------------+'
          echo '| make install                                                               |'
          make VERBOSE=1 -j1 install || (echo "Install failed for $APP"; read)
          echo '*============================================================================*'
          echo ''
          echo ''
          echo ''
          echo ''
 
done

################################################################################
# 2DX 
################################################################################

APP=2dx
echo '*============================================================================*'
echo '| ' ${APP}
echo '+----------------------------------------------------------------------------+'
echo '| prepare                                                                    |'
cd ${SRC}
echo 'workinkg directory: '
pwd
echo '+----------------------------------------------------------------------------+'
echo '| configure                                                                  |'
echo cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} . || (echo "Configure failed for" $APP ; read)
cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} . || (echo "Configure failed for" $APP ; read)
echo ''
echo '+----------------------------------------------------------------------------+'
echo '| make                                                                       |'
make VERBOSE=1 -j1 || (echo "Build failed for $APP"; read)
echo ''
echo '+----------------------------------------------------------------------------+'
echo '| make install                                                               |'
make VERBOSE=1 -j1 install || (echo "Install failed for $APP"; read)
echo '*============================================================================*'
echo ''
echo ''
echo ''
echo ''
 
cd ${BUILD}


