#!/bin/bash
#
# Package the bundle for Mac OS X 
#
# Marcel Arheit 17.09.2010

echo '*############################################################################*'
echo '| Making the Mac OS X installer package                                      |'
echo '*============================================================================*'
echo '|                                                                            |'
SYSTEM=`uname`
if [ $SYSTEM = "Darwin" ]
then
	SW_VERSION=`sw_vers -productVersion`
	DATE=`date "+%d_%b_%Y"`
	OUTFILE="2dx_MAC_OS_X_"$SW_VERSION"_"$DATE".pkg"
	PACKAGE_PATH="installation/packages/"
	echo "Writing the package "$OUTFILE" to: " $PACKAGE_PATH
	/Developer/usr/bin/packagemaker -d installation/mac_osx_installer/installer_template.pmdoc -o $PACKAGE_PATH$OUTFILE 

fi
echo '|                                                                            |'
echo '*============================================================================*'
echo ''
echo ''
echo ''
echo ''

