#!/bin/sh
#
#

rm -f /usr/bin/2dx
rm -f /usr/share/applications/2dx.desktop
rm -f /usr/share/pixmaps/2dx.png

rm -rf /usr/bin/2dx_image
rm -f /usr/share/applications/2dx_image.desktop
rm -f /usr/share/pixmaps/2dx_image.png

rm -rf /usr/bin/2dx_logbrowser
rm -f /usr/share/applications/2dx_logbrowser.desktop
rm -f /usr/share/pixmaps/2dx_logbrowser.png

exit 0