######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 21 09:46:25 2007
######################################################################

TEMPLATE = app
TARGET = 2dx_mrc2png
DEPENDPATH += .
INCLUDEPATH += . ../../../include
LIBS += -L../../../lib/common -lmrcImage

# Input
SOURCES += 2dx_mrc2png.cpp
