#!/bin/sh
#---------------------------------------------------------------------
# script to upload a file on the status website 
#---------------------------------------------------------------------
#
if [ $# -lt 4 ]
then
	echo "Error in reading arguments"
	echo "Usage: "
        echo "`basename $0:` <cadaver_executable> <server_url> <microscope> <status_dir>" >&2
	echo "Aborting!"
	exit 1
fi

echo '*############################################################################*'
echo '| Locating the files                                                         |'
echo '*============================================================================*'
echo '|                                                                            |'
#
CADAVER=$1
URL=$2
MICROSCOPE=$3
STATUSDIR=$4
#
if [ ! -d $STATUSDIR ]
then
	"Could not locate $STATUSDIR"
	exit 2;
fi
#
echo "Following files will be uploaded"
echo `ls -1 ${STATUSDIR}`
#

echo '|                                                                            |'
echo '*============================================================================*'
echo ''
echo ''
echo ''
echo ''


echo '*############################################################################*'
echo '| Uploading the files                                                        |'
echo '*============================================================================*'
echo '|                                                                            |'
#
sort -r ${STATUSDIR}/data.log > ${STATUSDIR}/sortdata.log
sort -r ${STATUSDIR}/last_recorded.txt > ${STATUSDIR}/last_recorded.txt.sorted
sort -r ${STATUSDIR}/last_imported.txt > ${STATUSDIR}/last_imported.txt.sorted
sort -r ${STATUSDIR}/last_processed.txt > ${STATUSDIR}/last_processed.txt.sorted
sort -r ${STATUSDIR}/last_errors.txt > ${STATUSDIR}/last_errors.txt.sorted
#
${CADAVER} ${URL} <<EOT
delete html/thumbnails/${MICROSCOPE}/*.png
delete html/thumbnails/${MICROSCOPE}/*.jpg
lcd ${STATUSDIR}
put last.txt html/logs/${MICROSCOPE}.last
put last_recorded.txt.sorted html/logs/${MICROSCOPE}.last_recorded
put last_imported.txt.sorted html/logs/${MICROSCOPE}.last_imported
put last_processed.txt.sorted html/logs/${MICROSCOPE}.last_processed
put last_errors.txt.sorted html/logs/${MICROSCOPE}.last_errors
put sortdata.log html/logs/${MICROSCOPE}.data
cd html/thumbnails/${MICROSCOPE}/
mput *.png
mput *.jpg
quit
EOT


echo '|                                                                            |'
echo '*============================================================================*'
echo ''
echo ''
echo ''
echo ''

