#!/bin/csh -ef
#############################################################################
#                                                                           #
# Title: Export to FREALIGN                                					#
#                                                                           #
# (C) 2dx.org, GNU Plublic License.                                         #
#                                                                           #
# Created..........: 29/07/2016                                             #
# Last Modification: 29/07/2016                                             #
# Author...........: 2dx.org                                                #
#                                                                           #
#############################################################################
#
# SORTORDER: 1
#
#
# MANUAL: Single Particle Refinement with FREALIGN and RELION (under construction)
#
# DISPLAY: SPR_RESMIN
# DISPLAY: SPR_RESMAX
# DISPLAY: SPR_SYM
# DISPLAY: SCRATCH_DISK
# DISPLAY: SPR_boxsize
# DISPLAY: SPR_PhaseShift
# DISPLAY: SPR_SIGCC
# DISPLAY: SPR_InvertContrast
# DISPLAY: SPR_NormalizeBox
# DISPLAY: SPR_CalculateDefocusTilted
# DISPLAY: SPR_SavePhaseFlipped
# DISPLAY: SPR_SaveWienerFiltered
# DISPLAY: SPR_SigmaNorm
# DISPLAY: SPR_WhichTiltGeometry
# DISPLAY: Thread_Number
# DISPLAY: CS
# DISPLAY: KV
# DISPLAY: sample_pixel
# DISPLAY: phacon
# DISPLAY: magnification
#
#$end_local_vars
#
set bin_2dx = ""
set proc_2dx = ""
set app_python = ""
set SCRATCH_DISK = ""
#
set SPR_RESMIN = ""
set SPR_RESMAX = ""
set SPR_SYM = ""
set SPR_PhaseShift = ""
set SPR_boxsize = ""
set SPR_SIGCC = ""
set SPR_InvertContrast = ""
set SPR_NormalizeBox = ""
set SPR_CalculateDefocusTilted = ""
set SPR_SavePhaseFlipped = ""
set SPR_SaveWienerFiltered = ""
set SPR_SigmaNorm = ""
set SPR_WhichTiltGeometry = ""
set CS = ""
set KV = ""
set Thread_Number = ""
set sample_pixel = ""
set phacon = ""
set magnification = ""
#
set SPR_IMGS_DIR = ${PWD}/../
set SPR_MERGEFILE = ${PWD}/2dx_merge_dirfile.dat
set SPR_STACKS_DIR = ${PWD}/SPR/stacks/
set SPR_FREALIGN_DIR = ${PWD}/SPR/frealign/
set SPR_PICKING_DIR = ${PWD}/SPR/picking/
set SPR_STACK_ROOTNAME = 'particles'
#$end_vars

# Start script commands:
mkdir -p ${SPR_STACKS_DIR}
mkdir -p ${SPR_FREALIGN_DIR}
mkdir -p ${SPR_PICKING_DIR}

${app_python} ${proc_2dx}/SPR_ExtractParticles.py ${SPR_IMGS_DIR} ${SPR_MERGEFILE} ${SPR_PICKING_DIR} ${SPR_STACKS_DIR} ${SPR_STACK_ROOTNAME} ${SPR_boxsize} ${SPR_PhaseShift} ${sample_pixel} ${KV} ${CS} ${phacon} ${magnification} ${SPR_SIGCC} ${SPR_InvertContrast} ${SPR_NormalizeBox} ${SPR_CalculateDefocusTilted} ${SPR_SavePhaseFlipped} ${SPR_SaveWienerFiltered} ${SPR_SigmaNorm} ${SPR_WhichTiltGeometry}

#${app_python} ${proc_2dx}/SPR_mparameters.py ${FREALIGN_DIR}
