#!/bin/sh
#
export INSTALL_DIR=$2
#
cd ${INSTALL_DIR}/bin
\rm -f 2dx_image.app
ln -sf ../2dx_image/2dx_image.app ./
\rm -f 2dx_merge.app
ln -sf ../2dx_merge/2dx_merge.app ./
\rm -f 2dx_logbrowser.app
ln -sf ../2dx_logbrowser/2dx_logbrowser.app ./
#
chown -RP root:wheel ${INSTALL_DIR}   
chmod -R 777 ${INSTALL_DIR}/kernel
#chown -RP $USER:wheel ${INSTALL_DIR}/kernel   
#

rm -f /usr/bin/2dx
ln -sf /opt/2dx/2dx_merge/2dx_merge.app/Contents/MacOS/2dx_merge /usr/bin/2dx

\rm -f /Applications/2dx
ln -sf ${INSTALL_DIR}/bin/2dx_merge.app /Applications/2dx
open /Applications
#
exit 0
