######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 5 12:04:08 2009
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += conf widgets mrcImage extentions
