######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 20 14:04:16 2010
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += conf widgets mrcImage extentions
