######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 25 09:39:23 2010
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += conf widgets mrcImage extentions
