	IMPLICIT NONE


C  we dont use units 5/6 for ttyin/out because these are connected
C  to stdin/stdout in al's fortran, and we want to feel free
C  to use stdin and stdout for files

C  we cant use stdin for -tone because of IMOPEN

	INTEGER*4       TTYIN
	  PARAMETER     (TTYIN=1)
	INTEGER*4       TTYOUT
	  PARAMETER     (TTYOUT=2)

C  function names
	INTEGER		LNBLNK

	REAL*4		DLOWER
	REAL*4		DRANGE
	REAL*4		DUPPER
	INTEGER*4	FIRSTSECTION
	REAL*4		HEIGHT
	LOGICAL		HEADER_REQD
	INTEGER*4	INTERPOLATE
	INTEGER*4	IOERR
	LOGICAL		LANDSCAPE
	LOGICAL		LOWER
	INTEGER*4	NSECTIONS
	CHARACTER	OUTPUTFILE*132
	CHARACTER	PARAM*256
	LOGICAL		REVERSE
	LOGICAL		RLE
	CHARACTER	SOURCEFILE*132
	LOGICAL		UPPER
	REAL*4		WIDTH
	REAL*4		XORIGIN
	REAL*4		YORIGIN


C  4-byte vars
	COMMON /TONECOMMON/	DLOWER
	COMMON /TONECOMMON/	DRANGE
	COMMON /TONECOMMON/	DUPPER
	COMMON /TONECOMMON/	FIRSTSECTION
	COMMON /TONECOMMON/	HEADER_REQD
	COMMON /TONECOMMON/	HEIGHT
	COMMON /TONECOMMON/	INTERPOLATE
	COMMON /TONECOMMON/	IOERR
	COMMON /TONECOMMON/	LANDSCAPE
	COMMON /TONECOMMON/	LOWER
	COMMON /TONECOMMON/	NSECTIONS
	COMMON /TONECOMMON/	REVERSE
	COMMON /TONECOMMON/	RLE
	COMMON /TONECOMMON/	UPPER
	COMMON /TONECOMMON/	WIDTH
	COMMON /TONECOMMON/	XORIGIN
	COMMON /TONECOMMON/	YORIGIN

C  1-byte vars
	COMMON /TONECOMMON/	OUTPUTFILE
	COMMON /TONECOMMON/	PARAM
	COMMON /TONECOMMON/	SOURCEFILE

