######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 20 13:54:16 2007
######################################################################

TEMPLATE = app
TARGET = ../../bin/2dx_spotIntensity.exe
DEPENDPATH += .
INCLUDEPATH += . ../../include ../../../../include
LIBS+=-L../../lib -L../../../../lib/common -l2dx -lconf
CONFIG-=app_bundle

# Input
HEADERS += ../../include/mrcImage.h
SOURCES += 2dx_spotIntensity.cpp
