# This script will generate a .star file given a list of input FOCUS image directories
#
set star_file_path = "${1}"
set img_list = "${2}"
set KV = "${3}"
set CS = "${4}"
set phacon = "${5}"
set ampcon = ` echo "scale=3; sqrt( 1 - ${phacon} * ${phacon} )" | bc `
#
#--------------------------------------------------------------------------------------
${proc_2dx}/linblock "StarFileGenerator: to generate a STAR file from selected images."
#--------------------------------------------------------------------------------------
#
#
if ( -e ${star_file_path} ) then
	\rm ${star_file_path}
endif

cat > ${star_file_path} << eot

data_

loop_
_rlnImageName #1
_rlnMicrographName #2
_rlnDefocusU #2
_rlnDefocusV #3
_rlnDefocusAngle #4
_rlnVoltage #5
_rlnSphericalAberration #6
_rlnAmplitudeContrast #7
_rlnPhaseShift #8
_rlnAngleRot #9
_rlnAngleTilt #10 
_rlnAnglePsi #11 
_rlnOriginX #12 
_rlnOriginY #13
eot

# cat ${img_list}
set tot_ptcls = 0
foreach img ( `cat ${img_list}` )

	set orimic = `grep imagename_original ../${img}/2dx_image.cfg | awk '{print $4}' | tr -d '"' | awk -F \/ '{print $NF}' `
	set orimicbase = `basename ${orimic} .mrc`
	
	if ( -e ../${img}/${orimicbase}_particles_prep.star) then

		echo ":: ${img}"

		# Get the number of preprocessed particles from this image:
		set nptcls = `tail -n +6 ../${img}/${orimicbase}_particles_prep.star | wc -l`
		# echo ":: ${nptcls}"
		# Remove the last empty line generated by relion_preprocess:
		@ nptcls -= 1
		set defocus = `grep "set defocus =" ../${img}/2dx_image.cfg | awk '{print $4}' | tr -d '"'`
		set defU = `echo ${defocus} | awk -F , '{print $1}'`
		set defV = `echo ${defocus} | awk -F , '{print $2}'`
		set ast = `echo ${defocus} | awk -F , '{print $3}'`
		set phaseshift = `grep defocus_phase_shift ../${img}/2dx_image.cfg | awk '{print $4}' | tr -d '"'`

		set i = 1
		while ( $i <= ${nptcls} )
			set iprint = `printf %.8d ${i}`
			echo "${iprint}@../${img}/${orimicbase}_particles_prep.mrcs  ${orimic}  ${defU}  ${defV}  ${ast}  ${KV}  ${CS}  ${ampcon}  ${phaseshift}  0.0  0.0  0.0  0.0  0.0" >> ${star_file_path}
			@ i += 1
			@ tot_ptcls += 1
		end

	endif

end
echo ":: "
echo ":: ${tot_ptcls} particles written to ${star_file_path}!"
echo ":: "

exit