#!/bin/bash
clear
export GREP_COLOR='3;32'
if [ $# -gt 0 ]; then
  
  if [ $# -gt 1 ]; then
    #cat ToDo.c | grep --color=always -i -E "(^\ *[^\/].*\[\ *$1\ *$2*\]|^#+[^#]+#+)" 
    #cat ToDo.c | awk '{if($0 ~ /^\ *-\ *\[\ *'$1'.*\]/) ENVIRON[level] = '$1'; else if( $0 ~ /^\ *-[^-]/ ) ENVIRON[level] = 0; if(($0 ~ /^\ *-\ *\['$1'\]/ || ($0 ~ /^\ *-+/ && ENVIRON[level] == "'$1'")) && $0 !~ /^\ *\/\// || $0 ~ /^\ *#+/) print $0;}' | grep --color=always -i -E "(^\ *[^\/].*\[\ *[0-9]+[^]]*\]|^#+[^#]+#+|^--+|)"
    echo "Usage: todo {priority}"
  else
    #cat ToDo.c | grep --color=always -E "(^\ *[^\/].*\[\ *$1[^]]*\]|^#+[^#]+#+)" 
    cat ToDo.c | awk '{if($0 ~ /^\ *-\ *\[\ *'$1'.*\]/) ENVIRON[level] = '$1'; else if( $0 ~ /^\ *-[^-]/ ) ENVIRON[level] = 0; if(($0 ~ /^\ *-\ *\[\ *'$1'.*\]/ || ($0 ~ /^\ *-+/ && ENVIRON[level] == "'$1'")) && $0 !~ /^\ *\/\// || $0 ~ /^\ *#+/) print $0;}' | grep --color=always -E "(^\ *[^\/].*\[\ *[0-9]+[^]]*\]|^#+[^#]+#+|^\ *--+)"
  fi
else
  #cat ToDo.c | grep --color=always -E "(^\ *[^\/].*\[\ *[0-9]+[^]]*\]|^#+[^#]+#+)"
    cat ToDo.c | grep --color=always -E "^\ *-|^\ *#+.*"
fi
