set(PACKAGE_VERSION @LIBVERSION@)

if(PACKAGE_FIND_NAME STREQUAL "@LIBTITLE@")
  if(PACKAGE_FIND_VERSION_MAJOR EQUAL @LIBVERSION@)
    set(PACKAGE_VERSION_COMPATIBLE true)
    set(PACKAGE_VERSION_EXACT      true)
  endif(PACKAGE_FIND_VERSION_MAJOR EQUAL @LIBVERSION@)
endif(PACKAGE_FIND_NAME STREQUAL "@LIBTITLE@")

