#!/bin/tcsh
#
/bin/rm -f *.o
/bin/rm -f *.f
/bin/rm -f Ximagelib.a
cp Ximagelibf.for Ximagelibf.f
f77 -extend_source -c Ximagelibf.f
cc -c Ximagelibc.c
ar r Ximagelib.a *.o
/bin/rm -f *.o
/bin/rm -f *.f
