message(STATUS "creating lib${LIB_NAME}.a")
file(GLOB OBJECT_FILES *.o)
message("OBJECT_FILES=${OBJECT_FILES}")
execute_process(COMMAND ar crs lib${LIB_NAME}.a ${OBJECT_FILES}) 
message("rm -f *.o *.f")
file(GLOB FSPLIT_FILES *.f)
execute_process(COMMAND rm -f ${OBJECT_FILES} ${FSPLIT_FILES}) 
execute_process(COMMAND ranlib lib${LIB_NAME}.a) 
