file(READ ${FSPLIT_INFILE} FSPLIT_FILE_STRING)
string(REGEX REPLACE ";" "\\\\;" FSPLIT_LIST "${FSPLIT_FILE_STRING}")
string(REGEX REPLACE "\n" ";" FSPLIT_LIST  "${FSPLIT_LIST}")
string(REGEX REPLACE " " ";" FORTRAN_FLAGS  "${FORTRAN_FLAGS}")
list(APPEND CMD ${FORTRAN_COMPILE_COMMAND})
list(APPEND CMD "-c")
list(APPEND CMD ${FORTRAN_FLAGS})
message(STATUS ${CMD})
foreach(FFILE ${FSPLIT_LIST})
	get_filename_component(FILENAME_WE ${FFILE} NAME_WE)	
	if(${FFILE} IS_NEWER_THAN ${FILENAME_WE}.o )
		message(STATUS "${FORTRAN_COMPILE_COMMAND} ${FORTRAN_FLAGS} -c ${FFILE}")
		execute_process(COMMAND ${CMD} ${FFILE})
	endif(${FFILE} IS_NEWER_THAN ${FILENAME_WE}.o )
endforeach(FFILE)
file(GLOB OBJ_FILES *.o)
#list(APPEND CMAKE_Fortran_FLAGS_RELEASE "-c")
#message(STATUS "gfortran -O3 -ffixed-line-length-none -fno-second-underscore -fdollar-ok -ffast-math -w ${FSPLIT_LIST}")
#execute_process(COMMAND gfortran -O3 -ffixed-line-length-none -fno-second-underscore -fdollar-ok -ffast-math -w ${FSPLIT_LIST})
#execute_process(COMMAND ${CMAKE_Fortran_COMPILER} ${CMAKE_Fortran_FLAGS_RELEASE}  ${FSPLIT_LIST})
