#!/bin/csh -ef
####
#
  #
  # This comes later, when there is a RAM-disk SCRATCH disk or similar:
  # if ( ! -e SCRATCH || ! -e FFTIR ) then
  #   2dx_linkscratch
  # endif
  #
  if ( ! -d proc ) then
    \mkdir proc
  endif
  #
  if ( ! -d LOGS ) then
    \mkdir LOGS
  endif
  #
  if ( ! -d SCRATCH ) then
    \mkdir SCRATCH
  endif
  #
  if ( ! -d FFTIR ) then
    \mkdir FFTIR
  endif
  #
  if ( ! -d APH ) then
    \mkdir APH
  endif
  #
  if ( ! -d PS ) then
    \rm -rf PS
    \mkdir PS
  endif
  #
  if ( ! -d CUT ) then
    \mkdir CUT
  endif
  #
  if ( ! -d PRJ ) then
    \mkdir PRJ
  endif
  #
#
