#!/bin/csh -ef
#############################################################################
#                                                                           #
# Title: Normalize Particles                                                #
#                                                                           #
# (C) 2dx.org, GNU Plublic License.                                         #
#                                                                           #
# Created..........: 16/10/2017                                             #
# Last Modification: 16/10/2017                                             #
# Author...........: Ricardo Righetto                                       #
#                                                                           #
#############################################################################
#
# SORTORDER: 50
#
# MANUAL: This script normalizes a particle stack extracted by Gautomatch
#
# DISPLAY: gautomatch_boxsize
# DISPLAY: rln_radnorm
# DISPLAY: rln_delraw
#
#$end_local_vars
set bin_2dx = ""
set proc_2dx = ""
set app_2dx_mrc_converter = ""
#
set rln_radnorm = ""
set rln_delraw = ""
set gautomatch_boxsize = ""
set movie_stackname = ""
#
#$end_vars
#
set scriptname = normalize_particles
\rm -f LOGS/${scriptname}.results
#
source ${proc_2dx}/initialize

if ( `echo "${rln_radnorm} < 1" | bc` ) then
	set rln_rad = `echo "${rln_radnorm} * ${gautomatch_boxsize}/2" | bc`
else
	set rln_rad = ${rln_radnorm}
endif

# Make sure that the radius is integer:
set rln_rad = `printf %.0f ${rln_rad}`
echo ":: "
echo ":: Particle will be normalized with a background radius equal to ${rln_rad} pixels."
echo ":: "
echo ":: "
echo "::Running:"
echo ":: "
echo ":: "${dir_relion}/bin/relion_preprocess
echo ":: "--operate_on ${movie_stackname}_particles.mrcs
echo ":: "--norm
echo ":: "--bg_radius ${rln_rad}
echo ":: "--operate_out ${movie_stackname}_particles_prep.mrcs
echo ":: "
#
${dir_relion}/bin/relion_preprocess \
--operate_on ${movie_stackname}_particles.mrcs \
--norm \
--bg_radius ${rln_rad} \
--operate_out ${movie_stackname}_particles_prep.mrcs \
#
\mv ${movie_stackname}_particles_prep.mrcs.mrcs ${movie_stackname}_particles_prep.mrcs
echo "#IMAGE-IMPORTANT: ${movie_stackname}_particles_prep.mrcs <Normalized particles>" >> LOGS/${scriptname}.results
#
if ( ${rln_delraw} == "y" ) then
	echo ":: "
	echo ":: rln_delraw = ${rln_delraw}"
	echo ":: WARNING: the original non-normalized particle stack will be deleted now!"
	echo ":: You may have to run the particle picking script again if changing picking/normalization parameters later."
	echo ":: "
	\rm ${movie_stackname}_particles.mrcs
endif
#
##########################################################################
${proc_2dx}/linblock "${scriptname} - normal end."
##########################################################################
#
exit
#