#!/bin/csh -ef
####
#
  #
  # This comes later, when there is a RAM-disk SCRATCH disk or similar:
  # if ( ! -e SCRATCH || ! -e FFTIR ) then
  #   2dx_linkscratch
  # endif
  #
  if ( ! -d SCRATCH ) then
    \mkdir SCRATCH
  endif
  #
  if ( ! -d LOGS ) then
    \mkdir LOGS
  endif
  #
  if ( ! -d APH ) then
    \mkdir APH
  endif
  #
  if ( ! -d PS ) then
    \mkdir PS
  endif
  #
  if ( ! -d PRJ ) then
    \mkdir PRJ
  endif
  #
  if ( ! -d RESULTS-MRC ) then
    \mkdir RESULTS-MRC
  endif
  #
  if ( ! -d RESULTS-PS ) then
    \mkdir RESULTS-PS
  endif
  #
  #
#
