#!/bin/sh
#
# This is not an executable script. It is only sourced from other scripts.
# The purpose of this script is to initiate the sub-directories, where all the different file types will be stored.
# It also allows specifying in the variable names SCRATCH_DISK and FFTIR_DISK locations for the sub-directories 
# SCRATCH and FFTR, which can then lie on a different drive. If that different drive is a very fast drive, e.g. in form
# of a RAM disk, then the overall processing performance for processing a larger number of images simultaneously 
# in several instances of 2dx_image will strongly increase.
#
# You could also implement that fast disk by placing it on a RAID-0 or RAID-5-managed hard-drive stack, or on a Solid-State drive.
#
####
#
  #
  # Create a SCRATCH disk on a fast drive, if the parameter SCRATCH_DISK is set
  if ( ${SCRATCH_DISK} == "." || ${SCRATCH_DISK}x == "x" ) then
    if ( ! -d SCRATCH ) then
      echo "::SCRATCH disk will be local."
      \mkdir SCRATCH
    endif
  else
    if ( ! -d SCRATCH && ! -l SCRATCH ) then
      set olddir = $PWD
      set newscratch = ${SCRATCH_DISK}/${olddir}
      if ( -d ${newscratch} ) then
        \rm -rf ${newscratch}
      endif
      \rm -rf SCRATCH
      echo "::SCRATCH disk will be:"
      echo "::${newscratch}"
      \mkdir -p ${newscratch}
      \ln -s ${newscratch} SCRATCH
    endif
  endif
  #
  # Create a SCRATCH disk on a fast drive, if the parameter SCRATCH_DISK is set
  if ( ${FFTIR_DISK} == "." || ${FFTIR_DISK}x == "x" ) then
    if ( ! -d FFTIR ) then
      echo "::FFTIR disk will be local."
      \mkdir FFTIR
    endif
  else
    if ( ! -d FFTIR && ! -l FFTIR ) then
      set olddir = $PWD
      set newfftir = ${FFTIR_DISK}/${olddir}
      if ( -d ${newfftir} ) then
        \rm -rf ${newfftir}
      endif
      \rm -rf FFTIR
      echo "::FFTIR disk will be:"
      echo "::${newfftir}"
      \mkdir -p ${newfftir}
      \ln -s ${newfftir} FFTIR
    endif
  endif
  #
  if ( ! -d proc ) then
    \mkdir proc
  endif
  #
  if ( ! -d LOGS ) then
    \mkdir LOGS
  endif
  #
  if ( ! -d APH ) then
    \mkdir APH
  endif
  #
  if ( ! -d PS ) then
    \mkdir PS
  endif
  #
  if ( ! -d CUT ) then
    \mkdir CUT
  endif
  #
  if ( ! -d PRJ ) then
    \mkdir PRJ
  endif
  #
#
