#!/bin/sh
#
export INSTALL_DIR=$2
#
echo "PROCESSING POSTINSTALL"
cd ${INSTALL_DIR}/bin
\rm -f focus.app
\rm -f fLogBrowser.app
\rm -f fMrcConverter.app
\rm -f fViewer.app
ln -sf ../focus/focus.app ./
ln -sf ../fLogBrowser/fLogBrowser.app ./
ln -sf ../fMrcConverter/fMrcConverter.app ./
ln -sf ../fViewer/fViewer.app ./
#
chown -RP root:wheel ${INSTALL_DIR}   
chmod -R 777 ${INSTALL_DIR}/kernel
#
open /Applications
#
cp /etc/profile /etc/profile.focus.bkp
echo "" >> /etc/profile
echo "# Focus environment variables" >> /etc/profile
echo "export PYTHONPATH=/opt/focus/scripts/proc:${PYTHONPATH}" >> /etc/profile
echo "export PATH=/opt/focus/scripts/proc:${PATH}" >> /etc/profile
echo "" >> /etc/profile
#
exit 0
